import { MetadataRoute } from 'next';
import { dbDataService } from '@/data/db-data-service';
import prisma from '@/lib/db';

/**
 * Generate dynamic sitemap for all published courses
 * This sitemap is automatically generated by Next.js and includes:
 * - Static pages (home, about, contact, etc.)
 * - All published courses
 * - All categories
 * - Featured courses page
 * 
 * Requirements: 13.1 - Generate sitemap.xml with all published courses
 */
export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://anywheredoor.com';
  
  // Static pages with high priority
  const staticPages: MetadataRoute.Sitemap = [
    {
      url: baseUrl,
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 1.0,
    },
    {
      url: `${baseUrl}/courses`,
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.9,
    },
    {
      url: `${baseUrl}/courses/featured`,
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/about`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.5,
    },
    {
      url: `${baseUrl}/contact`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.5,
    },
    {
      url: `${baseUrl}/instructors`,
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.6,
    },
  ];

  try {
    // Fetch all published courses from database
    const coursesResult = await dbDataService.getCourses({
      published: true,
      sortBy: 'updatedAt',
      sortOrder: 'desc',
      pageSize: 1000, // Get all courses for sitemap
    });

    // Generate sitemap entries for each published course
    const coursePages: MetadataRoute.Sitemap = coursesResult.courses.map((course) => ({
      url: `${baseUrl}/courses/${course.slug}`,
      lastModified: course.createdAt || new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    }));

    // Fetch all categories
    const categories = await prisma.category.findMany({
      select: {
        slug: true,
      },
    });

    // Generate sitemap entries for category pages
    const categoryPages: MetadataRoute.Sitemap = categories.map((category) => ({
      url: `${baseUrl}/courses/category/${category.slug}`,
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.7,
    }));

    // Combine all pages
    return [...staticPages, ...coursePages, ...categoryPages];
  } catch (error) {
    console.error('Error generating sitemap:', error);
    // Return static pages only if database query fails
    return staticPages;
  }
}
